const data = [
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Paneer Tikka",
        "description": "Tasty paneer tikka served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Starter",
        "price": 86,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyA2UWkaJJuxODm8JRetAxPKfIKtsM8Yw6LZ0MIpQHm72R1Jn93YtlKMg&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_3",
        "name": "Hara Bhara Kebab",
        "description": "Tasty hara bhara kebab served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Starter",
        "price": 78,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUxSm9uAv2V4N6rIRCA5JNGeWARtZx_pLVLOrmeuNZvNRgu4hZkl_C-VQ&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Chicken 65",
        "description": "Tasty chicken 65 served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Starter",
        "price": 155,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9tw6IvzttzTYx8deuP7q3MBHjGo1xRbqG-kxomyoLUgRW1a_knIx3Tfs&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Fish Fingers",
        "description": "Tasty fish fingers served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Starter",
        "price": 219,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGDp3HZ_AHuEhH5BwIziW7sA5ZA109lVH7ghgMxqqBGbbpbN2oChcSnlU&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Tandoori Chicken",
        "description": "Tasty tandoori chicken served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Starter",
        "price": 141,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy5bZzGdQ9JM_TIiFIGVnRlpkmYoRlfh32-V62V5LFXbsKiIDRwV6hdNg&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Veg Pakora",
        "description": "Tasty veg pakora served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Starter",
        "price": 275,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDLAGtJA9TDjj4hLKI4fY0KQS7RvJc9tEP-72Jcs8G0wTSn1nO2kpiHiI&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Spring Rolls",
        "description": "Tasty spring rolls served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Starter",
        "price": 120,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHMWnqr_UuUtL7YaaO_3bB0awvbsMj9IjrL_mrycenQ9Iw4kjkCVQa9eI&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Chilli Chicken",
        "description": "Tasty chilli chicken served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Starter",
        "price": 253,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR_2lavk8TZkSVHiz8ccLahVkhOu9JK-qMeKWdKT3wEd2rmUrAsHk4XIY&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_3",
        "name": "Veg Biryani",
        "description": "Tasty veg biryani served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Main Course",
        "price": 172,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy575iVN7yZ1u9nhz7_DotRNsUUtSw6X8RiQ2NJ6DE0DHzo7pKpGgw1JM&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Chicken Curry",
        "description": "Tasty chicken curry served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Main Course",
        "price": 60,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSln50kczTU_zxKciKOCxoVtjyqVz3EpxI8qbLkmeUCxP2KprxafBKbqPc&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Butter Chicken",
        "description": "Tasty butter chicken served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Main Course",
        "price": 120,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH_LpCLDrScRxK-I3rnF6og1_-VzNsdrLOI4n58ROqL3BA-k-S4WqVg9U&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Paneer Butter Masala",
        "description": "Tasty paneer butter masala served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Main Course",
        "price": 190,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2e7b-yo9eCAzTOQ8VbGQiDX7yW-ikS9Wtc6yC2V8X4DuPKVUeGlql-Ls&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Dal Tadka",
        "description": "Tasty dal tadka served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",    "category": "Main Course",
        "price": 81,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNhBmq2G4f5AFNAGCk9hl3STi3QdPHKp43EZ-_2mPpm0EeNLxuXbXGKMM&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_3",
        "name": "Rajma Chawal",
        "description": "Tasty rajma chawal served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Main Course",
        "price": 292,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOfzYB4ApVFZ5rTwOprU9dRcboL9b7QLUcYT-J-e0FSY7bzfmkSnKFuAA&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_3",
        "name": "Mutton Biryani",
        "description": "Tasty mutton biryani served fresh.",
        "type": "Non-Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2Fnonvegicon.svg&imgrefurl=https%3A%2F%2Fmuktifresh.in%2Fassets%2FfrontEnd%2Fimages%2F&docid=uAN0XsLNFvEZYM&tbnid=YFKlEQXFazWqsM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA..i&w=800&h=800&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECDsQAA",
        "category": "Main Course",
        "price": 93,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREkyulscP6Ii5FZi3UMZvVHj4SikREAZN-OagOsWHUuun9iponLC6Ny5E&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Kadhai Paneer",
        "description": "Tasty kadhai paneer served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Main Course",
        "price": 238,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIS7YBk7T6mzV4maLHEJIuWeXzpsqofrFH_rp9fQluNLXi5ZPQAQTNwQo&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Kheer",
        "description": "Tasty kheer served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Desserts",
        "price": 269,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-KzZQ_VFXGP6M7JewBpI495yXkEy5K43JU45d5ct9QDeQkJ3sVVMPwpE&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Rasgulla",
        "description": "Tasty rasgulla served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Desserts",
        "price": 148,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://source.unsplash.com/800x600/?Rasgulla",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Gulab Jamun",
        "description": "Tasty gulab jamun served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Desserts",
        "price": 253,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3Ty_OjZ7PzrWZWuCMO2H8wGCYU2EG6YNP3IfRnlS9k03I88UWO3B_rWA&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Jalebi",
        "description": "Tasty jalebi served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Desserts",
        "price": 166,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUWOQgUypkkO4Oynj5FOFtgNYTUxI3AMO0kvVBpxab_RazBKL-J2VyT2E&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Ice Cream",
        "description": "Tasty ice cream served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Desserts",
        "price": 252,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfKmaiVOcz28S_V0sstkMqVIuAO_G1Rrui0t33iGz3fz_d9vicEoT29V8&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_3",
        "name": "Fruit Custard",
        "description": "Tasty fruit custard served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Desserts",
        "price": 220,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbZaLkvXmRsphsIme6D4PvLUJLl9RMWmOFCmAqCUhY4YxPkw9HTw94wbE&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Lassi",
        "description": "Tasty lassi served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Beverages",
        "price": 203,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLnWROfPOKTk1M_2eAOtFKoFiXw5g8O-1BfhS3d8uBI3lMk-KGtodagQs&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Lime Soda",
        "description": "Tasty lime soda served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Beverages",
        "price": 254,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST9Hu3WJEhwC5YhQlcvX8HYuOXflrp_delRg8TTKn6gurH-JmLdgn4arA&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_3",
        "name": "Cold Coffee",
        "description": "Tasty cold coffee served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Beverages",
        "price": 250,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlhgjsFkS_zUrbxUcAFc-6mtdAF53t43LMML4v0YHxYe5TRR9KHbSqqEQ&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_2",
        "name": "Masala Chai",
        "description": "Tasty masala chai served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Beverages",
        "price": 268,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZXo5KPQWlLDJ55nkJlf578FYqtnRr94cmei8MUtnryB4kayFOfrMGDCA&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    },
    {
        "restaurantId": "RESTAURANT_ID_1",
        "name": "Fruit Juice",
        "description": "Tasty fruit juice served fresh.",
        "type": "Veg",
        "type_image" : "https://www.google.com/imgres?q=veg%20icon%20svg&imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F78%2FIndian-vegetarian-mark.svg%2F2048px-Indian-vegetarian-mark.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AIndian-vegetarian-mark.svg&docid=13t3GQvt8XZb-M&tbnid=4Xqqyd4vfwDrnM&vet=12ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA..i&w=2048&h=2048&hcb=2&ved=2ahUKEwio9uOwzKONAxW7XmwGHddWD1UQM3oECGoQAA",
        "category": "Beverages",
        "price": 136,
        "rating" : 4.5,
        "reviews" : "187",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb_VAjTO1qjFpd31xKvmMi3QSrHQ6oSYMDzmgcaNapOqyFoPi0O81RjaQ&s",
        "isBestseller": true,
        "isAvailable": true,
        "isCustomisable": true
    }
]